# Generated by Django 3.1.2 on 2020-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201031_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='data_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
