# Generated by Django 3.1.2 on 2020-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_article_data_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data_pub',
        ),
        migrations.AddField(
            model_name='article',
            name='date_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
