# Generated by Django 3.1.2 on 2020-10-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201031_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_pub',
            new_name='data_pub',
        ),
    ]
