# Generated by Django 3.1.2 on 2020-10-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201031_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='data_pub',
        ),
        migrations.AddField(
            model_name='article',
            name='date_pub',
            field=models.DateField(auto_now=True),
        ),
    ]
